### ISSUE TITLE
Can I see any examples or how can I use it?

### ISSUE THREAD

**Issue by daggerok** [tim-group/tg-eventstore#2]
Hello,

Do you have any examples. It's not clear how we can use it

---
Regards,
Maksim

**Comment by flicken** [comment]
@daggerok There are usage examples in the test here: https://github.com/tim-group/tg-eventstore/blob/d300ac027df3bb07f0219b3aad1cd66e8fac5da5/api/testlib/src/main/java/com/timgroup/eventstore/api/JavaEventStoreTest.java

What problem are you trying to solve that makes you consider using this library?

**Comment by daggerok** [comment]
Hello, @flicken,

Thanks, I'll look into tests.
What I'm looking for is some java event sourcing library/framework I can use...

---
Regards
